---
downloads: ~/.ansible-downloads/
osx_script: ~/.osx
username: mibu

configure_dotfiles: true
configure_ohmyzsh: true
configure_osx: true

configure_dock: false
dockitems_remove: []
dockitems_persist: []

configure_sudoers: false
sudoers_custom_config: ''

dotfiles_repo: https://github.com/mibu5/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .gitignore
  - .gitconfig
  - .osx

homebrew_installed_packages:
  # =======================================================================================================
  #    Programming Languages / Management
  # =======================================================================================================
  - nvm
  - git
  - git-delta
  - tfenv

  # =======================================================================================================
  #    Networking
  # =======================================================================================================
  - curl
  - dog

  # =======================================================================================================
  #    Data search / display / modify
  # =======================================================================================================
  - jq

  # =======================================================================================================
  #    System
  # =======================================================================================================
  - bottom

  # =======================================================================================================
  #    Terminal Setup
  # =======================================================================================================
  - bash
  - starship
  - tldr
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # Web
  - brave-browser
  - surfshark

  # Cloud Storage
  - dropbox

  # Security / Privacy
  - little-snitch
  - micro-snitch

  # Productivity
  - alfred
  - workflowy
  - fantastical

  # Communication
  - telegram
  - slack
  - zoom

  # Development
  - webstorm
  - iterm2
  - insomnia
  - visual-studio-code

  # Font
  - homebrew/cask-fonts/font-hack-nerd-font
  - homebrew/cask-fonts/font-fira-code
  - homebrew/cask-fonts/font-meslo-lg-nerd-font
  - homebrew/cask-fonts/font-meslo-for-powerline
  - homebrew/cask-fonts/font-monocraft
  - homebrew/cask-fonts/font-iosevka
  - homebrew/cask-fonts/font-iosevka-nerd-font
  - homebrew/cask-fonts/font-jetbrains-mono

  # Battery
  - aldente
  - coconutbattery

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - id: 441258766
    name: "Magnet"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
